---
dependency:
  name: galaxy
  options:
    # Bizarrely, Molecule treats this path completely differently from all
    # other paths that can be specified in this file.
    role-file: molecule/requirements.yml
lint: |
  ./scripts/lint.sh
driver:
  name: docker
platforms:
  - name: instance
    image: geerlingguy/docker-ubuntu1804-ansible:latest
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  playbooks:
    prepare: prepare.yml
verifier:
  name: ansible
  directory: ../../tests
